spring.application.name=Grand Store

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/store
spring.datasource.username=admin
spring.datasource.password=admin

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG