create table carts
(
    id           uuid primary key,
    date_created date not null default current_date
);

create table public.cart_items
(
    id         bigint generated by default as identity
        constraint cart_items_pk
            primary key,
    cart_id    uuid              not null
        constraint cart_items_carts_fk
            references public.carts (id)
            on delete cascade,
    product_id bigint            not null
        constraint cart_items_products_fk
            references public.products
            on delete cascade,
    quantity   integer default 1 not null,
    constraint cart_items_cart_product_unique
        unique (cart_id, product_id)
);

